Initial support for OpenHPC 4.0 on EL10
Signed-off-by: Timothy Middelkoop <tmiddelkoop@internet2.edu>

diff --git a/playbooks/ohpc-head-4.yaml b/playbooks/ohpc-head-4.yaml
--- a/playbooks/ohpc-head-4.yaml
+++ b/playbooks/ohpc-head-4.yaml
@@ -11,10 +11,10 @@
       ansible.builtin.template:
         owner: root
         group: root
-        mode: "644"
-        src: templates/ifcfg-eth1.j2
-        dest: /etc/sysconfig/network-scripts/ifcfg-eth1
-      register: networkmanager_eth1
+        mode: "600"
+        src: templates/enp0s2.nmconnection.j2
+        dest: /etc/NetworkManager/system-connections/ifcfg-enp0s2.nmconnection
+      register: networkmanager_enp0s2
 
     - name: Reload NetworkManager
       # noqa: no-handler
@@ -22,7 +22,7 @@
         name: NetworkManager.service
         enabled: true
         state: restarted
-      when: networkmanager_eth1.changed
+      when: networkmanager_enp0s2.changed
 
     - name: Check if firewalld is installed
       ansible.builtin.package_facts:
@@ -40,30 +40,32 @@
         path: /etc/hosts
         line: "10.5.0.8    head.localdomain head"
 
-    - name: Install OHPC release
-      ansible.builtin.dnf:
-        name: http://repos.openhpc.community/OpenHPC/3/EL_9/{{ ansible_architecture }}/ohpc-release-3-1.el9.{{ ansible_architecture }}.rpm
-        disable_gpg_check: true
+    ## FIXME: unreleased
+    # - name: Install OHPC release
+    #   ansible.builtin.dnf:
+    #     name: http://repos.openhpc.community/OpenHPC/4/EL_10/{{ ansible_architecture }}/ohpc-release-4-1.el10.{{ ansible_architecture }}.rpm
+    #     disable_gpg_check: true
 
-    - name: Add OpenHPC Release Factory (3.4)
+    - name: Add OpenHPC Release Factory (4.0)
       ansible.builtin.yum_repository:
         name: openhpc-factory
         description: OpenHPC Factory Repository
-        baseurl: http://obs.openhpc.community:82/OpenHPC3:/3.4:/Factory/EL_9/
+        baseurl: http://obs.openhpc.community:82/OpenHPC4:/4.0:/Factory/EL_10/
         enabled: "{{ ohpc_factory | bool }}"
         gpgcheck: false
 
     - name: Install OHPC base
       ansible.builtin.dnf:
+        ## FIXME: broken or can be removed
         name:
-          - ohpc-base
+          # - ohpc-base
           - ohpc-slurm-client
           - ohpc-slurm-server
-          - hwloc-ohpc
+          # - hwloc-ohpc
           - chrony
           - jq
-          - mtools
-          - initscripts-service # AlmaLinux
+          # - mtools
+          # - initscripts-service # AlmaLinux
 
     - name: Install Warewulf (OHPC)
       when: ohpc_warewulf
@@ -96,6 +98,7 @@
       # noqa: command-instead-of-module
       ansible.builtin.shell: |-
         set -e -x
+        set -o pipefail
 
         sms_name=head
         sms_ip=10.5.0.8
@@ -105,19 +108,39 @@
         dns_servers=8.8.8.8
         dhcp_start=10.5.1.1
         dhcp_end=10.5.1.254
+        sms_eth_internal=enp0s2
 
-        sed -i "s/^ipaddr:.*/ipaddr: ${sms_ip}/" /etc/warewulf/warewulf.conf
-        sed -i "s/^netmask:.*/netmask: ${internal_netmask}/" /etc/warewulf/warewulf.conf
-        sed -i "s/network:.*/network: ${internal_network}/" /etc/warewulf/warewulf.conf
-        sed -i "s/template: default/template: static/" /etc/warewulf/warewulf.conf
-        sed -i "/range start:/d;/range end:/d;" /etc/warewulf/warewulf.conf
-        sed -i "s/mount: false/mount: true/" /etc/warewulf/warewulf.conf
-        sed -i "s/mntops: defaults,noauto,nofail/mntops: defaults,nofail/" /etc/warewulf/nodes.conf
-        sed -i "/- quiet/d" /etc/warewulf/nodes.conf
+        ## Cleanup failed setup
+        wwctl profile delete nodes || true
+        wwctl image delete --yes rocky-10 || true
+        userdel --remove auser || true
+
+        ## FIXME: yq
+        dnf install -y https://kojipkgs.fedoraproject.org/packages/yq/4.43.1/5.fc40/aarch64/yq-4.43.1-5.fc40.aarch64.rpm
+
+        ## Configure warewulf.conf
+        yq -i /etc/warewulf/warewulf.conf --from-file /dev/stdin <<EOF
+          .ipaddr = "${sms_ip}" |
+          .netmask = "${internal_netmask}" |
+          .network = "${internal_network}" |
+          .dhcp["template"] = "static" |
+          .dhcp["range start"] = "${dhcp_start}" |
+          .dhcp["range end"] = "${dhcp_end}" |
+          .dhcp["systemd name"] = "dnsmasq" |
+          .tftp["systemd name"] = "dnsmasq" |
+          .ssh["key types"] -= ["dsa"]
+        EOF
 
         ## Warewulf
         wwctl configure --all
         bash /etc/profile.d/ssh_setup.sh # setup ssh
+
+        ## Configure dnsmasq
+        echo "interface=${sms_eth_internal}" > /etc/dnsmasq.d/ww4-interface.conf
+
+        ## FIXME: missing arm64 ipxe
+        install -dvp /var/lib/tftpboot/warewulf/arm64-efi
+        cp -v /usr/share/ipxe/arm64-efi/snponly.efi /var/lib/tftpboot/warewulf/arm64-efi/snponly.efi
 
         ## Slurm
         cp /etc/slurm/slurm.conf.ohpc /etc/slurm/slurm.conf
@@ -133,13 +156,18 @@
         systemctl enable --now slurmctld
 
         ## Import node image
-        wwctl image import docker://ghcr.io/warewulf/warewulf-rockylinux:9 rocky-9 --syncuser
+        wwctl image import docker://ghcr.io/warewulf/warewulf-rockylinux:10 rocky-10 --syncuser
 
         ## Create "nodes" profile and inherit settings from the "default" profile
         wwctl profile add nodes --profile=default --comment="Nodes profile"
 
         ## Configure "default" network (netname) for "nodes" profile
         wwctl profile set --yes nodes --netname=default --netmask=${internal_netmask} --gateway=${ipv4_gateway} --nettagadd=DNS=${dns_servers}
+
+        ## Update kernel args for debug messages
+        yq -i /etc/warewulf/nodes.conf --from-file /dev/stdin <<EOF
+          .nodeprofiles.default.kernel.args -= ["quiet"]
+        EOF
 
         ## Create a test user
         useradd --create-home --shell=/bin/bash --user-group auser
@@ -161,7 +189,7 @@
         arch=$(uname -m)
 
         ## Configure image
-        wwctl image exec rocky-9 /bin/bash << EXEC
+        wwctl image exec rocky-10 /bin/bash << EXEC
         ## --------------------------------------------------------------------
         set -e -x
         export LANG=C.UTF-8
@@ -176,20 +204,32 @@
         passwd -d root # allow serial console login
 
         {% if ohpc_factory | default(false) %}
-        dnf config-manager --add-repo http://obs.openhpc.community:82/OpenHPC3:/3.4:/Factory/EL_9/
+        ## FIXME: verify that the OpenHPC Factory packages are not signed
+        #dnf config-manager --add-repo http://obs.openhpc.community:82/OpenHPC4:/4.0:/Factory/EL_10/
+        cat > /etc/yum.repos.d/openhpc.repo <<EOF
+        [openhpc-factory]
+        name=OpenHPC Factory Repository
+        baseurl=http://obs.openhpc.community:82/OpenHPC4:/4.0:/Factory/EL_10/
+        enabled=1
+        gpgcheck=0
+        EOF
         {% endif %}
-        dnf install -y http://repos.openhpc.community/OpenHPC/3/EL_9/${arch}/ohpc-release-3-1.el9.${arch}.rpm
+        ## FIXME: not yet released
+        # dnf install -y http://repos.openhpc.community/OpenHPC/4/EL_10/${arch}/ohpc-release-4-0.el10.${arch}.rpm
+
+        # enabled services go here
+        install -dvp /etc/systemd/system-preset
 
         dnf install -y ohpc-base-compute hwloc-ohpc
         dnf install -y ohpc-slurm-client
 
-        systemctl enable munge
+        echo "enable munge.service" > /etc/systemd/system-preset/90-munge.preset
 
         dnf install -y chrony
         echo "server ${sms_ip} iburst" >> /etc/chrony.conf
 
         echo SLURMD_OPTIONS="--conf-server ${sms_ip}" > /etc/sysconfig/slurmd
-        systemctl enable slurmd
+        echo "enable slurmd.service" > /etc/systemd/system-preset/90-slurmd.preset
 
         dnf install -y lmod-ohpc
 
@@ -208,8 +248,8 @@
         wwctl profile set --yes nodes --system-overlays munge --runtime-overlays syncuser
 
         ## Set as default image and set kernel args
-        wwctl profile set --yes nodes --image rocky-9
-        wwctl profile set --yes nodes --kernelargs='console=tty0,"console=ttyS0,115200",systemd.log_color=0,crashkernel=no,vga=791,rd.shell'
+        wwctl profile set --yes nodes --image rocky-10
+        wwctl profile set --yes nodes --kernelargs='"console=ttyS0,115200",systemd.log_color=0,crashkernel=no,vga=791,rd.shell'
 
         touch /root/configure-node-image.stamp
 
